### ISSUE TITLE
fix: recovery relay camera preview renders nothing after changing cameras

### ISSUE THREAD

**Issue by Burry** [fireblocks/recovery#2]
After selecting a different camera in the Recovery Relay QR code scanner, the preview briefly renders the new camera feed and then nothing.

**Comment by ArielSir-fb** [comment]
@agoltzman, switching cameras is working fine for me. It renders and scans QR.
A I missing what's the issue here?

**Comment by agoltzman** [comment]
If the issue doesn't replicate you can close it
