### ISSUE TITLE
feat: offer windows version of the recovery tool

### ISSUE THREAD

**Issue by m8nky** [fireblocks/recovery#30]
Use case:
As a representative of an institution, where the IT policy is Windows only, I would like to operate the recovery in the institutional environment.

**Comment by agoltzman** [comment]
Hi @m8nky,

We appreciate the feedback on this. This is something we are checking to see if and when we can provide such a version however it is not part of the next several versions.
In case you are in fact a Fireblocks customer I suggest that you reach out to your Account Manager or Customer Success manager to forward this request to our product team.

Thanks again!
