### ISSUE TITLE
fix: failure creating new asset wallet for multiple chains

### ISSUE THREAD

**Issue by ArielSir-fb** [fireblocks/recovery#36]
After recovery, when adding asset wallets within a vault, it fails to do so for the next chains:
BSV
DASH
DOGE
LTC
ZEC
XDB

`Failed to create new wallet (DASH): _lib_wallets__WEBPACK_IMPORTED_MODULE_5__.WalletClasses[nativeAssetId] is not a constructor`

**Comment by agoltzman** [comment]
Closing, split into #46, #47, #48, #49, #50 & #51
