### ISSUE TITLE
Import Vault Data fails with 0.4.0

### ISSUE THREAD

**Issue by m8nky** [fireblocks/recovery#52]
**NEVER PROVIDE ANY PART OF YOUR RECOVERY KIT, KEYS, OR OTHER INFORMATION AS PART OF THIS ISSUE - NO MEMBER OF FIREBLOCKS WILL EVER ASK FOR SUCH INFORMATION**
**MAKE SURE TO OBFUSCATE ANY SENSETIVE DATA FROM YOUR SCREENSHOTS OR STEPS**

**Describe the bug**
After recovering the keys, I want to import the Vault Data to generate transactions. The CSV from Fireblocks worked in 0.3.5.

Is the assumption correct, the 0.4.0 Ubuntu package contains the latest release, but is tagges as 0.3.5 still?

The error message is: Row contains invalid characters - please reset workspace and check your importing CSV.

**To Reproduce**
After recovery / verification (Choose one): Yes

If the issue is after recovery or verification, simply write the steps after the recovery (no need to provide the recovery steps unless requested)
1. Click Import/Export
2. Select 'Fireblocks_vault_addresses.csv'
3. Click 'Import'

**Expected behavior**
Import of addresses suceeds.

**Desktop (please complete the following information):**
 - OS and version: Linux

**Additional context**
Log:
[2023-12-15 09:59:45.539] [debug] csvImport {
  sanatizedData: {
    'Account Name': 'Name is ok',
    'Account ID': 2,
    Asset: 'MATIC_POLYGON',
    'Asset Name': 'Matic Gas Token (Polygon)',
    Address: '0x...',
    'Address Type': 'Permanent',
    'Address Description': null,
    Tag: null,
    'HD Path': 'm / 44 / 60 / 2 / 0 / 0'
  },
  errors: []
}
[2023-12-15 09:59:45.539] [error] Error: Row contains prohibited characters - please reset workspace and check your importing CSV
    at parseRow (app://index.html/_next/static/chunks/pages/_app-8696f24e2a413b52.js:389:302732)
    at Worker.step [as userStep] (app://index.html/_next/static/chunks/pages/_app-8696f24e2a413b52.js:389:303802)
    at Worker._ (app://index.html/_next/static/chunks/pages/_app-8696f24e2a413b52.js:398:19434)

The error is logged for all rows imported.

**Comment by agoltzman** [comment]
Resolved in v0.4.1
