### ISSUE TITLE
feat: security warning popups for initiating recovery and revealing private keys

### ISSUE THREAD

**Issue by Burry** [fireblocks/recovery#9]
Display a security warning popup advising that the machine must be in a secure, offline environment with only authorized personnel present. Present options "Cancel" and "Continue".

Show these popups when:
- The user clicks the "Recover Private Keys" button on the splash screen
- The user clicks the reveal button for extended or derived private keys

**Comment by ArielSir-fb** [comment]
@agoltzman I added the pop-up for revealing the xprv/fprv. There is already a pop-up for the recover button itself.
Do we also want to add the pop-up to each individual asset wallet? I feel this might be a bit over-redundant.

**Comment by agoltzman** [comment]
@ArielSir-fb - please create a modal and not an alert.
See example [here](https://github.com/fireblocks/recovery/blob/main/apps/recovery-utility/renderer/pages/setup.tsx#L372) [here](https://github.com/fireblocks/recovery/blob/main/apps/recovery-utility/renderer/pages/setup.tsx#L373) or [here](https://github.com/fireblocks/recovery/blob/main/apps/recovery-utility/renderer/components/RecoveryForm/index.tsx#L213)
